"use client";

import { useEffect, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { X, Sparkles } from "lucide-react";

export default function AIBuiltModal() {
  const [open, setOpen] = useState(false);

  useEffect(() => {
    const timer = setTimeout(() => setOpen(true), 1800);
    return () => clearTimeout(timer);
  }, []);

  useEffect(() => {
    if (open) {
      document.body.style.overflow = "hidden";
    } else {
      document.body.style.overflow = "";
    }
    return () => { document.body.style.overflow = ""; };
  }, [open]);

  const close = () => setOpen(false);

  return (
    <AnimatePresence>
      {open && (
        <>
          {/* Backdrop */}
          <motion.div
            key="backdrop"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.3 }}
            onClick={close}
            className="fixed inset-0 z-[9998] bg-[#0B0B0B]/60 backdrop-blur-sm"
          />

          {/* Modal */}
          <motion.div
            key="modal"
            initial={{ opacity: 0, scale: 0.92, y: 24 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.94, y: 16 }}
            transition={{ duration: 0.45, ease: [0.34, 1.56, 0.64, 1] }}
            className="fixed inset-0 z-[9999] flex items-center justify-center px-4"
          >
            <div
              className="relative w-full max-w-md bg-[#0B0B0B] text-white overflow-hidden"
              style={{
                boxShadow: "0 24px 64px rgba(239,43,36,0.18), 0 4px 16px rgba(11,11,11,0.4)",
                borderRadius: "4px",
              }}
            >
              {/* Red accent bar at top */}
              <div className="h-1 w-full bg-[#EF2B24]" />

              {/* Header */}
              <div className="flex items-start justify-between px-7 pt-6 pb-0">
                <div className="flex items-center gap-2.5">
                  <div className="flex items-center justify-center w-8 h-8 rounded-lg bg-[#EF2B24]/15 border border-[#EF2B24]/25">
                    <Sparkles size={15} className="text-[#EF2B24]" strokeWidth={1.8} />
                  </div>
                  <span className="text-[10px] font-bold tracking-[0.22em] uppercase text-white/40">
                    Behind This Site
                  </span>
                </div>

                <button
                  onClick={close}
                  className="text-white/30 hover:text-white transition-colors duration-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#EF2B24] focus-visible:ring-offset-2 focus-visible:ring-offset-[#0B0B0B] rounded active:scale-[0.95]"
                  aria-label="Close"
                >
                  <X size={18} strokeWidth={2} />
                </button>
              </div>

              {/* Body */}
              <div className="px-7 pt-5 pb-7">
                <h2
                  className="text-2xl font-black tracking-[-0.01em] text-white mb-3 leading-tight uppercase"
                  style={{ fontFamily: "var(--font-poiret)" }}
                >
                  100% Built by{" "}
                  <span className="text-[#EF2B24]">AI.</span>
                </h2>

                <p className="text-sm text-white/55 leading-[1.85] mb-5">
                  Every pixel, component, and line of code on this portfolio was
                  generated by{" "}
                  <span className="text-white font-semibold">Claude Code</span>
                  {" "}— Anthropic&apos;s AI coding agent — without any manual code editing.
                </p>

                <p className="text-sm text-white/55 leading-[1.85] mb-7">
                  Design system, animations, responsive layout, and all interactions
                  were crafted entirely through conversation.{" "}
                  <span className="text-white/75">This is what AI-assisted engineering looks like.</span>
                </p>

                {/* Stat chips */}
                <div className="flex flex-wrap gap-2 mb-7">
                  {[
                    { dot: "#EF2B24", label: "Next.js App Router" },
                    { dot: "#2F56A6", label: "Tailwind CSS v4" },
                    { dot: "#3BB44A", label: "Framer Motion" },
                    { dot: "#F5B21B", label: "Claude Code" },
                  ].map(({ dot, label }) => (
                    <span
                      key={label}
                      className="inline-flex items-center gap-1.5 px-3 py-1 text-[11px] font-semibold tracking-wide text-white/60 border border-white/10 rounded-full"
                    >
                      <span style={{ color: dot }}>●</span>
                      {label}
                    </span>
                  ))}
                </div>

                {/* Divider */}
                <div className="h-px w-full bg-white/08 mb-6" />

                {/* CTA row */}
                <div className="flex items-center justify-between gap-4">
                  <p className="text-[11px] text-white/25 leading-relaxed max-w-[180px]">
                    Human direction.{" "}
                    <span className="text-white/40">AI execution.</span>
                  </p>
                  <button
                    onClick={close}
                    className="inline-flex items-center gap-2 px-5 py-2.5 bg-[#EF2B24] text-white text-xs font-bold tracking-[0.14em] uppercase transition-[transform,opacity] duration-200 hover:opacity-90 active:scale-[0.97] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#EF2B24] focus-visible:ring-offset-2 focus-visible:ring-offset-[#0B0B0B]"
                  >
                    Got It
                  </button>
                </div>
              </div>
            </div>
          </motion.div>
        </>
      )}
    </AnimatePresence>
  );
}
